version: '3.7'

services:
  nginx:
    container_name: nginx
    networks:
      - inception
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on: 
      - wordpress
    ports:
      - 443:443

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on: 
      - mariadb

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress
  mariadb_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mariadb

networks:
  inception:
    driver: bridge